### ISSUE TITLE
JavaScriptCore framework crashed the application.

### ISSUE THREAD

**Issue by nishithcitc** [adobe/webkit#1]
Here is the stack trace of crash report.

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib          0x0000000197140ef0 swtch_pri + 8
1   libsystem_pthread.dylib         0x00000001971f83dc sched_yield + 12
2   JavaScriptCore                  0x00000001869e9da0 JSC::JSLock::grabAllLocks(JSC::JSLock::DropAllLocks_, unsigned int) + 48
3   JavaScriptCore                  0x00000001866b201c JSC::JSLock::DropAllLocks::~DropAllLocks() + 36
4   JavaScriptCore                  0x000000018697702c JSC::DelayedReleaseScope::~DelayedReleaseScope() + 180
5   JavaScriptCore                  0x00000001866c7648 JSC::MarkedAllocator::allocateSlowCase(unsigned long) + 484
6   JavaScriptCore                  0x000000018673df64 JSC::LiteralParser<unsigned char>::parse(JSC::ParserState) + 4428
7   JavaScriptCore                  0x00000001866f7558 JSC::LiteralParser<unsigned char>::tryJSONPParse(WTF::Vector<JSC::JSONPData, 0ul, WTF::CrashOnOverflow>&, bool) + 2304
8   JavaScriptCore                  0x00000001866f4c60 JSC::Interpreter::execute(JSC::ProgramExecutable_, JSC::ExecState_, JSC::JSObject_) + 372
9   JavaScriptCore                  0x00000001866f4978 JSC::evaluate(JSC::ExecState_, JSC::SourceCode const&, JSC::JSValue, JSC::JSValue_) + 472
10  JavaScriptCore                  0x00000001869c8e94 JSEvaluateScript + 404
11  JavaScriptCore                  0x00000001869d24d0 -[JSContext evaluateScript:withSourceURL:] + 112
12  WebApp              0x00000001000d88dc 0x1000b0000 + 166108
13  Foundation                      0x00000001860e417c **NSFireDelayedPerform + 420
14  CoreFoundation                  0x00000001851a8128 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 24
15  CoreFoundation                  0x00000001851a7dd8 __CFRunLoopDoTimer + 884
16  CoreFoundation                  0x00000001851a5824 __CFRunLoopRun + 1368
17  CoreFoundation                  0x00000001850d12d0 CFRunLoopRunSpecific + 392
18  GraphicsServices                0x000000018e8ef6f8 GSEventRunModal + 164
19  UIKit                           0x0000000189c96fa8 UIApplicationMain + 1484

**Comment by dirkschulze** [comment]
Please report crashes in Safari to Apples bug tracker.
