### ISSUE TITLE
Help making the font-feature-settings property available in WebKit

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe/webkit#2]
Seen from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings), Safari had given up the `font-feature-settings` CSS property since 6.0, this property require advanced typographic feature support for OpenType fonts, so I hope you can help them to get support for this property in WebKit, and making it available in newer version of Safari.

Additionaly, you can also try to get support or improve for `@font-feature-values`, `font-language-override`, `font-variant`, `font-variant-alternates`, `font-variant-caps`, `font-variant-east-asian`, `font-variant-ligatures`, `font-variant-numeric`, `font-variant-position` properties based on this work.

**Comment by dirkschulze** [comment]
@KrasnayaPloshchad This is a fork of the official WebKit repository that hasn't been updated in 4 years. Maybe you want to look at https://github.com/WebKit/webkit

**Comment by KrasnayaPloshchad** [comment]
@dirkschulze Thank you.
