### ISSUE TITLE
I need help with Canvas2DLayerBridge.

### ISSUE THREAD

**Issue by dnwldbs84** [adobe/webkit#4]
Hi. 

Recently I launched a game website. When I'm alone on the server, I have no problem, but if I`m in with a few users [even just five users] on the same server the performance gradually drops. [This is happening to many users who using chrome.]
 In the Chrome JavaScript profiler, there is a phenomenon that the proportion of (program) increases over time. If I click on another tab in Google Chrome and click on the My Site tab again, the portion occupied by (program) is to be initialized [it seems to be (idle)]. But soon the specs are down. 
 So I used chrome: // tracing / and found Canvas2DLayerBridge to grow. This phenomenon was not found until I had drawn more than a certain amount on the canvas. How can I handle this? 

* There is no problem with other browsers (ie, firefox, opera).
* The client is fully developed in JavaScript.
* Test environment is Windows 7, Chrome version is 64.0.3282.140.

**Comment by dirkschulze** [comment]
@dnwldbs84 This is not an official repository. Furthermore, issues in Chrome should be reported to the Chrome bug tracker (or Blink bug tracker).
